In [1]:
import numpy as np
import pandas as pd

Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [3]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item,'is non-zero')

2 is non-zero
3 is non-zero
1 is non-zero
Zero value found at Index 3
6 is non-zero
7 is non-zero


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [5]:
df = pd.DataFrame([[1,2,complex(3,6)],[4,5,6],[7,8,9],[np.inf,-np.inf,np.nan]])
np.isfinite(df)

0      1      2
0   True   True   True
1   True   True   True
2   True   True   True
3  False  False  False

Write a NumPy program to test element-wise for positive or negative infinity.

In [6]:
np.isinf(df)

0      1      2
0  False  False  False
1  False  False  False
2  False  False  False
3   True   True  False

Write a NumPy program to test element-wise for NaN of a given array.

In [9]:
df = pd.DataFrame([[1,2,complex(3,6)],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]])
print(df)
print('=========================')
not_nan=np.isnan(df)
not_nan

     0    1         2
0  1.0  2.0  3.0+6.0j
1  4.0  5.0  6.0+0.0j
2  7.0  8.0  9.0+0.0j
3  NaN  NaN N000a000N


0      1      2
0  False  False  False
1  False  False  False
2  False  False  False
3   True   True   True

Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.


In [8]:
complex_num=np.iscomplex(df)
print(complex_num)
print('==============================')
not_nan=np.isnan(df)
print(not_nan)
print('==============================')
print(np.isscalar(1))

[[False False  True]
 [False False False]
 [False False False]
 [False False False]]
       0      1      2
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False   True
True


Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [10]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[1,2,3], [4,1,5]]) 
np.isclose(a,b)

array([[ True,  True,  True],
       [False, False,  True]])

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [11]:
c = np.equal(a,b)
print(c)
print('========================')
d = np.less_equal(a,b)
print(d)
print('========================')
e = np.not_equal(a,b)
print(e)
print('========================')
f = np.greater_equal(a,b)
print(f)

[[ True  True  True]
 [False False  True]]
[[ True  True  True]
 [ True False  True]]
[[False False False]
 [ True  True False]]
[[ True  True  True]
 [False  True  True]]


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [12]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[1,2,3], [4,1,5]]) 
np.isclose(a,b)

array([[ True,  True,  True],
       [False, False,  True]])

Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.


In [13]:
a = np.array([1,7,13,105])
a.nbytes

16

In [14]:
print('%d bytes'%(a.size*a.itemsize))

16 bytes
