# Assessment 4: Numerical Python

In [63]:
import numpy as np
import cmath

We use the following as our arrays for this work

In [79]:
a=np.array([1,0,5,np.nan,np.inf])
b=np.array([1,0,np.isneginf,-1,5])

#### Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [80]:
def non_zero_test(value):#You must pass in an array
    for index,value in enumerate(value): 
        if value!=0:
            print('{} is non-zero'.format(value))
        else:
            print("Your number is zero") 
non_zero_test(a)

1.0 is non-zero
Your number is zero
5.0 is non-zero
nan is non-zero
inf is non-zero


#### Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [81]:
np.isfinite(a) 

array([ True,  True,  True, False, False])

#### Write a NumPy program to test element-wise for positive or negative infinity.

In [82]:
np.isneginf(a)

array([False, False, False, False, False])

In [83]:
np.isposinf(a)

array([False, False, False, False,  True])

#### Write a NumPy program to test element-wise for NaN of a given array.

In [84]:
np.isnan(a)

array([False, False, False,  True, False])

#### Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [85]:
np.iscomplex(b)

array([False, False, False, False, False])

In [86]:
np.isscalar(a)

False

#### Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [87]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))


False


#### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [88]:
list(np.array(a) == np.array(b))

[True, True, False, False, False]

In [89]:
list( np.array([1,4,1]) > np.array([1,2,1]))

[False, True, False]

In [90]:
 list(np.array([1,4,1]) < np.array([1,2,1]))


[False, False, False]

In [91]:
np.equal(a,b)

array([ True,  True, False, False, False])

#### Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [92]:
c=np.array([1,7,13,105])
memory_size=c.size*c.itemsize
print("The size of the memory is:",memory_size)


The size of the memory is: 32
