# Tasks

1. Write a NumPy program to test whether none of the elements of a given array is zero

In [1]:
import numpy as np

In [4]:
a = np.array([3,4,7,3,0,8])
print("The original array is:")
a

The original array is:


array([3, 4, 7, 3, 0, 8])

To test whether none of the elements of a given array is zero:

In [5]:
for elements in a:
    if elements == 0:
        print(elements,"is a zero value.")
    else:
        print(elements, "is not a zero value.")

3 is not a zero value.
4 is not a zero value.
7 is not a zero value.
3 is not a zero value.
0 is a zero value.
8 is not a zero value.


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [6]:
b = np.array([5,10,0,0,3,500])
print("The original array of b is:")
b

The original array of b is:


array([  5,  10,   0,   0,   3, 500])

To test whether any of the elements of a given array is non-zero:

In [9]:
for items in b:
    if items != 0:
        print( items, "is non-zero")
    else:
        print(items, "is a zero value")

5 is non-zero
10 is non-zero
0 is a zero value
0 is a zero value
3 is non-zero
500 is non-zero


3. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [13]:
c = np.array([5,6,np.nan,np.inf,8])
c = np.isfinite(c)
for index, elements in enumerate(c):
    if elements == True:
        print('Index:', index, "is finite:",elements)
    else:
        print('Index:', index, "is not a number and is infinite:", elements)

Index: 0 is finite: True
Index: 1 is finite: True
Index: 2 is not a number and is infinite: False
Index: 3 is not a number and is infinite: False
Index: 4 is finite: True


4. Write a NumPy program to test element-wise for positive or negative infinity.

In [19]:
d = np.array([50, np.inf, -np.inf, 250])
print("The original array of d is:")
d

The original array of d is:


array([ 50.,  inf, -inf, 250.])

To test the array element-wise for positive or negative infinity:

In [18]:
print("When the element in the array is a negative infinity, the Boolean value is: ")
print(np.isneginf(d))
print("===================================")
print("When the element in the array is a positive infinity, the Boolean value is: ")
print(np.isposinf(d))

When the element in the array is a negative infinity, the Boolean value is: 
[False False  True False]
When the element in the array is a positive infinity, the Boolean value is: 
[False  True False False]


5. Write a NumPy program to test element-wise for NaN of a given array.

6. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

7. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

8. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

9. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.