# Week 4 Assessment

## 1.
## Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np
a = np.array([0, 2, 2, 3, 5, 7, 7])
b = np.array([4, 4, 6, 6, 9, 9, 1])

print("The arrays are given as", "\n", a, "\n", b)


The arrays are given as 
 [0 2 2 3 5 7 7] 
 [4 4 6 6 9 9 1]


### Element-wise comparison (greater)

In [2]:
greater_comp = np.greater(a, b)
print(greater_comp)

[False False False False False False  True]


### Element-Wise comparison (greater_equal)

In [3]:
# returns a boolean
greater_equal = np.greater_equal(a, b)
print(greater_equal)

[False False False False False False  True]


### Element-Wise comparison (less)

In [4]:
less_comp = np.less(a, b)
print(less_comp)

[ True  True  True  True  True  True False]


### Element-Wise comaprison (less_equal)

In [5]:
less_equal = np.less_equal(a, b)
print(less_equal)

[ True  True  True  True  True  True False]


## 2

## Create an element-wise comparison (equal, equal within a tolerance) of two given arrays

In [6]:
c = np.array([888, 105, 89, -123, -189, 234, 450, 0, 99, 75])
d = np.array([111, -105, 88.99, -123.2, 188.8, 234, 450.999, 0.001, 99, 75.0000])

print("The arrays are given as", "\n", c, "\n", d)


The arrays are given as 
 [ 888  105   89 -123 -189  234  450    0   99   75] 
 [ 1.11000e+02 -1.05000e+02  8.89900e+01 -1.23200e+02  1.88800e+02
  2.34000e+02  4.50999e+02  1.00000e-03  9.90000e+01  7.50000e+01]


### Element-Wise comparison (equal)

In [7]:
equal_tol = np.equal(c, d)
print(equal_tol)

[False False False False False  True False False  True  True]


### Element-Wise comparison (equal within tolerance)

In [8]:
equal_within = np.allclose(c, d)
print(equal_within)

False


## 3.

## Write a NumPy program to test element-wise for NaN of a given array

In [9]:
e = np.array([10, 0, 0, np.inf, 5, np.nan, np.sqrt(-64)])
print("The arrays are given as", "\n", e)


The arrays are given as 
 [10.  0.  0. inf  5. nan nan]


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


### Testing element-wise for NaN

In [10]:
test_nan = np.isnan(e)
print(test_nan)

[False False False False False  True  True]


## 4

## Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [11]:
f = np.array([5, 10.8, 0+3j, -5-1j, 3+5j, 20])
ff = np.sqrt([-25, 4, -1, -64, 1+4J])

print("The arrays are given as", "\n", f, "\n", ff)

The arrays are given as 
 [ 5. +0.j 10.8+0.j  0. +3.j -5. -1.j  3. +5.j 20. +0.j] 
 [0.        +5.j         2.        +0.j         0.        +1.j
 0.        +8.j         1.60048518+1.24962107j]


### Testing element-wise for complex number

In [12]:
g = np.iscomplex(f)
gg = np.iscomplex(ff)
print(g, "\n", gg)

[False False  True  True  True False] 
 [ True False  True  True  True]


### Testing element-wise for real number

In [13]:
h = np.isreal(f)
print(h)

[ True  True False False False  True]


### Testing for scalar within the given array

In [14]:
print(f[4], " is scalar? ", np.isscalar(f[4]))
print(f[5], " is scalar? ", np.isscalar(f[5]))

(3+5j)  is scalar?  True
(20+0j)  is scalar?  True


## 5

## Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [15]:
j = np.array([1, 7, 13, 105])

print(j)

[  1   7  13 105]


### Determining the size of the memory occupied by the array

In [16]:
print("The size of the memory occupied by array ", j, " is ", (j.size * j.itemsize), "bytes")

The size of the memory occupied by array  [  1   7  13 105]  is  16 bytes


## 6

## Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [17]:
k = np.array([1e12, 1e-8, 1e-5, 1e10])
l = np.array([1.00e12, 1e-8, 1e-5, 1.000e10])
m = np.array([1.0001e12, 1e-7, 1e-6, 1.0001e11])
n = np.array([2.5, 3.99995, np.nan, np.nan])

print("The arrays are given as", "\n", k, "\n", l, "\n", m, "\n", n)
print("\n")
print(np.allclose(k, l))
print(np.allclose(k, m))
print(np.allclose(n,n))
print(np.allclose(n,n,equal_nan=True))


The arrays are given as 
 [1.e+12 1.e-08 1.e-05 1.e+10] 
 [1.e+12 1.e-08 1.e-05 1.e+10] 
 [1.0001e+12 1.0000e-07 1.0000e-06 1.0001e+11] 
 [2.5     3.99995     nan     nan]


True
False
False
True
