# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

#### Numpy 2D Array

In [2]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [3]:
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [4]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [5]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [6]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [7]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

**Subsetting 2D NumPy Arrays**

In [8]:
a[0]

array([1, 2, 3])

In [9]:
a[0][0] # Accessing the first element from the first array

1

In [10]:
a[1][0] # Accessing the first element from the second array

4

In [11]:
a[0][1:2] # Accessing from index 1 to 2 elements from the first array

array([2])

In [12]:
a[1][1:2] # Accessing from index 1 to 2 elements from the second array

array([1])

**2D Arithmetic**

In [13]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [14]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [15]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [16]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

##### Task

1. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [19]:
#NOTE: I FOUND THE ANSWER BUT I DONT KNOW WHAT HAPPENED HERE!
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))  

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [21]:
import numpy as np
x= np.array([1,2,3,4,6])
y= np.array([6,4,3,9,6])
print ("original numbers")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

original numbers
[1 2 3 4 6]
[6 4 3 9 6]
Comparison - greater
[False False False False False]
Comparison - greater_equal
[False False  True False  True]
Comparison - less
[ True  True False  True False]
Comparison - less_equal
[ True  True  True  True  True]
