# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

#### Numpy 2D Array

In [2]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [3]:
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [4]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [5]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [6]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [7]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

**Subsetting 2D NumPy Arrays**

In [8]:
a[0]

array([1, 2, 3])

In [9]:
a[0][0] # Accessing the first element from the first array

1

In [10]:
a[1][0] # Accessing the first element from the second array

4

In [11]:
a[0][1:2] # Accessing from index 1 to 2 elements from the first array

array([2])

In [12]:
a[1][1:2] # Accessing from index 1 to 2 elements from the second array

array([1])

**2D Arithmetic**

In [13]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [14]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [15]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [16]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

##### Task

1. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [17]:
print(np.allclose([1e10,1e-7],[1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8],[1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8],[1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan],[1.0,np.nan]))
print(np.allclose([1.0, np.nan],[1.0,np.nan], equal_nan = True))

False
True
False
False
True


2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [27]:
b = np.array([[4,5,6],[7,8,9]])
print("Arrays:")
print(a)
print(b)
print("++++++++++++++++++++++")
print("Greater")
print(np.greater(a,b))
print("Greater_equal")
print(np.greater_equal(a,b))
print("Less")
print(np.less(a,b))
print("Less_equal")
print(np.less_equal(a,b))

Arrays:
[[1 2 3]
 [4 1 5]]
[[4 5 6]
 [7 8 9]]
++++++++++++++++++++++
Greater
[[False False False]
 [False False False]]
Greater_equal
[[False False False]
 [False False False]]
Less
[[ True  True  True]
 [ True  True  True]]
Less_equal
[[ True  True  True]
 [ True  True  True]]
