# Exercise Notebook (DS)

In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

#### Numpy 2D Array

In [3]:
a = np.array([[1,2,3],[3,4,5]])
print(a)

[[1 2 3]
 [3 4 5]]


In [8]:
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [4]:
# Addition
a+3

array([[4, 5, 6],
       [6, 7, 8]])

In [5]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [6]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [7]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])

**Subsetting 2D NumPy Arrays**

In [9]:
a[0]

array([1, 2, 3])

In [10]:
a[0][0] # Accessing the first element from the first array

1

In [11]:
a[1][0] # Accessing the first element from the second array

4

In [12]:
a[0][1:2] # Accessing from index 1 to 2 elements from the first array

array([2])

In [15]:
a[1][1:2] # Accessing from index 1 to 2 elements from the second array

array([1])

**2D Arithmetic**

In [ ]:
# Addition
a+3

In [ ]:
# Multiplication
a*2

In [ ]:
# Subtraction
a-2

In [ ]:
# Division
a/3

##### Task

1. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [2]:
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


2. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [3]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]
