## Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np

In [31]:
x = np.array([20, 23, 8, 9, 15])
print(x)
print(np.all(x))

y = np.array([0, 20, 8, 9, 23])
print(y)
print(np.all(y))

[20 23  8  9 15]
True
[ 0 20  8  9 23]
False


## Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [33]:
x = np.array([0, 23, 8, 9, 15])
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

y = np.array([0, 0, 0, 0, 0])
print(y)
print("Test whether any of the elements of a given array is non-zero:")
print(np.all(y))

[ 0 23  8  9 15]
Test whether any of the elements of a given array is non-zero:
True
[0 0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


## Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).


In [34]:
x = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(x)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(x))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


## Write a NumPy program to test element-wise for positive or negative infinity.

In [36]:
import numpy as np
x = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(x)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(x))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


 ## Write a NumPy program to test element-wise for NaN of a given array.

In [37]:
x = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(x)
print("Test element-wise for NaN:")
print(np.isnan(x))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


## Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [39]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(x))
print("Checking for real number:")
print(np.isreal(x))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1 2]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


## Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [40]:
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


## Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [41]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


## Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [42]:
x = np.array([75, 77, 80, 95, 170, -125, 110, -20, 70, 100])
y = np.array([75, 77, 80, 95, 170, -125, 110, -20, 70, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  75   77   80   95  170 -125  110  -20   70  100]
[  75.         77.         80.         95.        170.       -125.
  110.        -20.         70.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


## Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [43]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes
