In [1]:
import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
import numpy as np

In [3]:
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [4]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


In [5]:
for index, item in enumerate(a):
    if item!=0:
        print('Element is non-zero, Item is', item)
    else:
        print(item, 'is found at index', index)

Element is non-zero, Item is 2
Element is non-zero, Item is 3
Element is non-zero, Item is 1
0 is found at index 3
Element is non-zero, Item is 6
Element is non-zero, Item is 7


In [22]:
#not infinity or not a number
a = np.array([1,np.inf, 2, 8,3,4,5,np.nan])
np.isfinite(a)

array([ True, False,  True,  True,  True,  True,  True, False])

In [23]:
#element-wise for positive infinity
a = np.array([1,-np.inf, 2, 8,3,4,5,np.inf])
np.isposinf(a)

array([False, False, False, False, False, False, False,  True])

In [24]:
#element-wise for negative infinity
a = np.array([1,-np.inf, 2, 8,3,4,5,-np.nan])
np.isneginf(a)

array([False,  True, False, False, False, False, False, False])

In [25]:
a = np.array([1, 0, np.nan, np.inf])
a
np.isnan(a)

array([False, False,  True, False])

In [31]:
a = np.array([4.5, 3+1j, 2, 1+0j, 3, 2j, 4])
a

array([4.5+0.j, 3. +1.j, 2. +0.j, 1. +0.j, 3. +0.j, 0. +2.j, 4. +0.j])

In [32]:
np.iscomplex(a)

array([False,  True, False, False, False,  True, False])

In [33]:
np.isreal(a)

array([ True, False,  True,  True,  True, False,  True])

In [34]:
np.isscalar(3.1)

True

In [35]:
np.isscalar([3.1])

False

In [40]:
a = np.array([2,3,1,0,6,7])
b = np.array([4,5,9,0,8,2])
#np.allclose([2,3,1,0,6,7], [4,5,9,0,8,2], equal_nan=True)
np.allclose(a, b, equal_nan=True)

False

In [42]:
a = np.array([2,3,1,0,6,7])
b = np.array([4,5,9,0,8,2])
np.greater(a,b)

array([False, False, False, False, False,  True])

In [44]:
np.greater_equal(a,b)

array([False, False, False,  True, False,  True])

In [45]:
np.greater_equal(b,a)

array([ True,  True,  True,  True,  True, False])

In [46]:
np.less(a,b)

array([ True,  True,  True, False,  True, False])

In [48]:
np.less(b,a)

array([False, False, False, False, False,  True])

In [47]:
np.less_equal(a,b)

array([ True,  True,  True,  True,  True, False])

In [49]:
np.equal(a,b)

array([False, False, False,  True, False, False])

In [53]:
np.allclose(a, b)

False

In [66]:
c = np.array([1,7,13,105])
c

array([  1,   7,  13, 105])

In [67]:
print("Size of the memory occupied by the said array:", "%d bytes" % (c.size * c.itemsize))

Size of the memory occupied by the said array: 16 bytes
