In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)
import numpy as np

## More on NumPy - Arithmetic Operations

Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules.

**Example**

In [2]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
a  

First array:


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [3]:
print('Second array:' )
b = np.array([10,5,10]) 
b

Second array:


array([10,  5, 10])

In [4]:
print('Add the two arrays:') 
np.add(a,b)  

Add the two arrays:


array([[10.,  6., 12.],
       [13.,  9., 15.],
       [16., 12., 18.]])

In [5]:
print('Subtract the two arrays:') 
np.subtract(a,b)

Subtract the two arrays:


array([[-10.,  -4.,  -8.],
       [ -7.,  -1.,  -5.],
       [ -4.,   2.,  -2.]])

In [6]:
print('Multiply the two arrays:') 
np.multiply(a,b)

Multiply the two arrays:


array([[ 0.,  5., 20.],
       [30., 20., 50.],
       [60., 35., 80.]])

In [7]:
print('Divide the two arrays:' )
np.divide(a,b)

Divide the two arrays:


array([[0. , 0.2, 0.2],
       [0.3, 0.8, 0.5],
       [0.6, 1.4, 0.8]])

**More arithmetics can be performed with the following:**

- numpy.reciprocal()

This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the result is always 0 because of the way in which Python handles integer division. For integer 0, an overflow warning is issued.

- numpy.power()

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

- numpy.mod()

This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result.

## Statistical Functions

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc. from the given elements in the array.

**numpy.amin() and numpy.amax()**
These functions return the minimum and the maximum from the elements in the given array along the specified axis.

**Example**

In [8]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Our array is:' )
a

Our array is:


array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [18]:
X=ROWS (1)
Y=COLUMNS (0)

NameError: name 'ROWS' is not defined

In [10]:
print('Applying amin() function:') 
np.amin(a,1)

Applying amin() function:


array([3, 3, 2])

In [19]:
print('Applying amin() function again:') 
np.amin(a,0) 

Applying amin() function again:


array([2, 4, 3])

In [20]:
print('Applying amax() function:') 
np.amax(a)

Applying amax() function:


9

In [21]:
print('Applying amax() function again:') 
np.amax(a, axis = 0)

Applying amax() function again:


array([8, 7, 9])

**numpy.ptp()**
- The numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

In [22]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Our array is:') 
a

Our array is:


array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [23]:
print('Applying ptp() function:') 
np.ptp(a) 

Applying ptp() function:


7

In [24]:
print('Applying ptp() function along axis 1:') 
np.ptp(a, axis = 1) 

Applying ptp() function along axis 1:


array([4, 5, 7])

In [25]:
print('Applying ptp() function along axis 0:')
np.ptp(a, axis = 0)

Applying ptp() function along axis 0:


array([6, 3, 6])

**numpy.percentile()**

- Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage of observations in a group of observations fall. The function numpy.percentile() takes the following arguments.

`numpy.percentile(a, q, axis)`

a: Input array
	
q: The percentile to compute must be between 0-100
	
axis: The axis along which the percentile is to be calculated

In [26]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [27]:
print('Applying percentile() function:') 
np.percentile(a,50)

Applying percentile() function:


50.0

In [28]:
print('Applying percentile() function along axis 1:') 
np.percentile(a,50, axis = 1)

Applying percentile() function along axis 1:


array([40., 20., 60.])

**numpy.median()**

- Median is defined as the value separating the higher half of a data sample from the lower half. The **numpy.median()** function is used as shown in the following program.

**Example**

In [30]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print('Our array is:') 
a   

Our array is:


array([[30, 65, 70],
       [80, 95, 10],
       [50, 90, 60]])

In [31]:
print('Applying median() function:') 
np.median(a) 

Applying median() function:


65.0

In [32]:
print('Applying median() function along axis 0:') 
np.median(a, axis = 0)

Applying median() function along axis 0:


array([50., 90., 60.])

In [33]:
print('Applying median() function along axis 0:') 
np.median(a, axis = 1)

Applying median() function along axis 0:


array([65., 80., 60.])

**numpy.mean()**

- Arithmetic mean is the sum of elements along an axis divided by the number of elements. The **numpy.mean()** function returns the arithmetic mean of elements in the array. If the axis is mentioned, it is calculated along it.

**Example**


In [34]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
a   

Our array is:


array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [35]:
print('Applying mean() function:') 
print(np.mean(a)) 

Applying mean() function:
3.6666666666666665


In [36]:
print('Applying mean() function along axis 0:') 
np.mean(a, axis = 0)

Applying mean() function along axis 0:


array([2.66666667, 3.66666667, 4.66666667])

In [37]:
print('Applying mean() function along axis 1:') 
np.mean(a, axis = 1)

Applying mean() function along axis 1:


array([2., 4., 5.])

**numpy.average()**

- Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

- Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by adding the product of the corresponding elements and dividing the sum by the sum of weights.

`Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)`

**Example**

In [38]:
a = np.array([1,2,3,4]) 

print('Our array is:') 
a  

Our array is:


array([1, 2, 3, 4])

In [39]:
print('Applying average() function:') 
np.average(a) 

Applying average() function:


2.5

In [40]:
np.mean(a)

2.5

In [45]:
# this is same as mean when weight is not specified 
wts = np.array([4,3,2,1]) 

In [44]:
np.mean(wts)

2.5

In [46]:
print('Applying average() function again:') 
np.average(a,weights = wts)

Applying average() function again:


2.0

In [47]:
# Returns the sum of weights, if the returned parameter is set to True. 
print('Sum of weights') 
np.average([1,2,3, 4],weights = [4,3,2,1], returned = True)

Sum of weights


(2.0, 10.0)

##### Task

1. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [51]:
a = np.array([73, 80, 85, 90, 150, -134, 121, -11, 62, 100])
b = np.array([71, 78, 85, 91, 152, -136, 123, -14, 62, 100.000001])
print(a)
print(b)
print("Comparison - equal:")
print(np.equal(a, b))
print("Comparison - equal within a tolerance:")
print(np.allclose(a, b))


[  73   80   85   90  150 -134  121  -11   62  100]
[  71.         78.         85.         91.        152.       -136.
  123.        -14.         62.        100.000001]
Comparison - equal:
[False False  True False False False False False  True False]
Comparison - equal within a tolerance:
False


2. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [52]:
a = np.array([1, 7, 13, 105])
print("Original array:")
print(a)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (a.size * a.itemsize))


Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes
