In [1]:
# this code conceals irrelevant warning messages
import warnings
warnings.simplefilter('ignore', FutureWarning)

## Exercise 1: Numpy


### Numpy

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

#### Operations using NumPy (IMPORTANCE)
Using NumPy, a developer can perform the following operations:


1. Mathematical and logical operations on arrays.
2. Fourier transforms (In mathematics, a Fourier series (/ˈfʊrieɪ, -iər/) is a periodic function composed of harmonically related sinusoids, combined by a weighted summation. ... The process of deriving the weights that describe a given function is a form of Fourier analysis.) and routines for shape manipulation.
3. Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

An instance of ndarray class can be constructed by different array creation routines described later in the tutorial. 
The basic ndarray is created using an array function in NumPy as follows

In [8]:
import numpy 

In [9]:
numpy.array

<function numpy.array>

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [10]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

# The above constructor takes the following parameters

#### Sr.No.	Parameter & Description:

1. object

Any object exposing the array interface method returns an array, or any (nested) sequence.

2. dtype

Desired data type of array, optional

3. copy

Optional. By default (true), the object is copied

4. order

C (row major) or F (column major) or A (any) (default)

5. subok

By default, returned array forced to be a base class array. If true, sub-classes passed through

6. ndmin

Specifies minimum dimensions of resultant array








Note: All arithmetic operations can be perform on a numpy array

In [11]:
import numpy as np

`Examples`

__Operations on Numpy Array__

In [12]:
# Base Ball Player's Heights AS a in 2D 
a = np.array([[1,2,3], [4,1,5]]) 
print (a)

[[1 2 3]
 [4 1 5]]


In [13]:
# Addition
a+3

array([[4, 5, 6],
       [7, 4, 8]])

In [14]:
# Multiplication
a*2

array([[ 2,  4,  6],
       [ 8,  2, 10]])

In [15]:
# Subtraction
a-2

array([[-1,  0,  1],
       [ 2, -1,  3]])

In [16]:
# Division
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 0.33333333, 1.66666667]])

__Task__

1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [17]:
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [18]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


2.  Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [20]:
b = np.array([2,1,3,6,7])
b

array([2, 1, 3, 6, 7])

In [22]:
for index,item in enumerate(b):
    if item==0:
        print('None zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
1  is not zero
3  is not zero
6  is not zero
7  is not zero
