Write a NumPy program to test whether none of the elements of a given array is zero.


In [1]:
import numpy as np


In [10]:
a= np.array([1,2,3,5])
b= np.array([0,3,5,6])
print(np.all(a))
print(np.all(b))


True
False


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [31]:
a= np.array([1,2,3,5])
b= np.array([0,0,0,0])
print(np.any(a),np.any(b))


True False


Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [29]:
x= np.array([4,0,np.nan,np.inf])
np.isfinite(x)

array([ True,  True, False, False])

Write a NumPy program to test element-wise for positive or negative infinity.

In [28]:
y=np.array([1,0,np.nan, -np.inf,np.inf])
np.isinf(y)


array([False, False, False,  True,  True])

Write a NumPy program to test element-wise for NaN of a given array.

In [26]:
x=np.array([3,5,0,np.nan,np.inf])
np.isnan(x)

array([False, False, False,  True, False])

Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [47]:
z= np.array([3+2j, 4, 5.1,6j])
print(np.iscomplex(z))
print(np.isreal(z))
print(np.isscalar(z),np.isscalar(3))

[ True False False  True]
[False  True  True False]
False True


Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [56]:
x= np.array([3,4,5,-10,10])
y= np.array([3,4,5,-10,10.001])

np.allclose(x,y)


False

Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [54]:
x = np.array([5,8])
y = np.array([2,8])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True False]
[ True  True]
[False False]
[False  True]


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [55]:
x= np.array([3,4,5,-10,10])
y= np.array([3,4,5,-10,10.001])
print(np.equal(x,y)) 
print(np.allclose(x,y))

[ True  True  True  True False]
False


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [66]:
k= np.array([1,7,13,105])
print("%d bytes" % (k.size * k.itemsize))

16 bytes
