# Task 1
Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [2]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


In [3]:
for index,item in enumerate (a):
    if item !=0:
        print('Non-zero value found at Index', index)
    else:
        print(item, 'is zero')

Non-zero value found at Index 0
Non-zero value found at Index 1
Non-zero value found at Index 2
0 is zero
Non-zero value found at Index 4
Non-zero value found at Index 5


# Task 2
Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [5]:
print(np.isfinite(a))

[ True  True  True  True  True  True]


Write a NumPy program to test element-wise for positive or negative infinity.

In [6]:
print(np.isinf(a))

[False False False False False False]


# Task 3
Write a NumPy program to test element-wise for NaN of a given array.

In [9]:
b = np.array([1,5,10,np.nan,5,85,63,np.inf])
b

array([ 1.,  5., 10., nan,  5., 85., 63., inf])

In [10]:
print(np.isnan(b))

[False False False  True False False False False]


Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
​


In [12]:
c = np.array([1,12,5,2j,5,48,1+0j,6j])
c

array([ 1.+0.j, 12.+0.j,  5.+0.j,  0.+2.j,  5.+0.j, 48.+0.j,  1.+0.j,
        0.+6.j])

In [13]:
print("complex numbers check")
print(np.iscomplex(c))

complex numbers check
[False False False  True False False False  True]


In [14]:
print("real numbers check")
print(np.isreal(c))

real numbers check
[ True  True  True False  True  True  True False]


In [18]:
print("scalar check 1")
print(np.isscalar(3))

print("scalar check 2")
print(np.isscalar ([3,5]))

scalar check 1
True
scalar check 2
False


# Task 4
Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [21]:
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [23]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x,y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


# Task 5

Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [25]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [26]:
X = np.array([1, 7, 13, 105])
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes
