# 1. Write a NumPy program to test whether any of the elements of a given array is non-zero.

Solution:

In [11]:
import numpy as np

In [12]:
array = np.array([7,10,4,0,0,2,556])
print(array)
  
# Test whether any of the elements of a given array is non-zero
print("=====================")
print(np.any(array))

[  7  10   4   0   0   2 556]
True


# 2. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

Solution:

In [13]:
a = np.array([1, 0, np.nan, np.inf])

print("Original array")
print(a)

print('===============')

print("To test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
To test a given array element-wise for finiteness :
[ True  True False False]


# 3. Write a NumPy program to test element-wise for positive or negative infinity.

Solution:

In [4]:
b = np.array([3, 0, np.nan, np.inf])
print("Original array")
print(b)

print("====================")

print("To test element-wise for positive or negative infinity:")
print(np.isinf(b))

Original array
[ 3.  0. nan inf]
To test element-wise for positive or negative infinity:
[False False False  True]


# 4. Write a NumPy program to test element-wise for NaN of a given array.

Solution:

In [14]:
c = np.array([5, 0, np.nan, np.inf])
print("Original array")
print(c)
print('=======================')
print("Test element-wise for NaN:")
print(np.isnan(c))

Original array
[ 5.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


# 5. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

Solution:

In [15]:

d = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(d)
print('==============')



print("Checking for complex number:")
print(np.iscomplex(d))
print('========================')

print("Checking for real number:")
print(np.isreal(d))
print("=================")


print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


# 6. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

Solution:

In [16]:
print("To test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

To test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


# 7. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

Solution:

In [17]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print('=====================')
print("Comparison - greater")
print(np.greater(x, y))
print('=====================')

print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print('======================')

print("Comparison - less")
print(np.less(x, y))
print('=====================')

print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


# 8. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

Solution:

In [18]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print('===================')
print("Comparison - equal:")
print(np.equal(x, y))
print('===================')
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


# 9. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

Solution:

In [19]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print('======================')
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes
