# Exercise 7
# operator to perform arithmetic addition on two numbers


In [29]:
print (1 + 2)
# to merge two lists
print ("Two" + "Lists")
# Concatenate two strings
print ("Two"*3)

3
TwoLists
TwoTwoTwo


# Exercise 8
# Write a NumPy program to test whether none of the elements of a given array is zero.

In [7]:
import numpy as np
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [8]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


# Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [10]:
import numpy as np
a = np.array([10,33,56,89,0,3,8,9,0,6])
print("Original array")
print(a)
print("Test whether any of the elements of a given array is non-zero")
print(np.any(a))
a = np.array([10,33,56,89,0,3,8,9,0,6])
print("Original array:")
print(a)
print("Test whether any of the elements of a give array is non-zero")
print(np.any(a))
        

Original array
[10 33 56 89  0  3  8  9  0  6]
Test whether any of the elements of a given array is non-zero
True
Original array:
[10 33 56 89  0  3  8  9  0  6]
Test whether any of the elements of a give array is non-zero
True


# Exercise 9

# 1.Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).


In [30]:
import numpy as np
a = np.array([23, 0, 1, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[23.  0.  1. nan inf]
Test a given array element-wise for finiteness :
[ True  True  True False False]


# 2.Write a NumPy program to test element-wise for positive or negative infinity.


In [ ]:
import numpy as np
a = np.array([23, 0, 1, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity :")
print(np.isinf(np.inf))
print(np.isinf(np.nan))
print(np.isinf(np.NINF))

# Exercise 10

# Write a NumPy program to test element-wise for NaN of a given array.

In [16]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wisefor NaN :")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wisefor NaN :
[False False  True False]


# Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not. 

In [18]:
import numpy as np
a = np.array([1+1j, 1+0j, 8, 0, 5j])
print("Original array")
print(a)
print("Checking for complex number :")
print(np.iscomplex(a))
print("Checking for real number : ")
print(np.isreal(a))
print("Checking for scalar type :")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1.+1.j 1.+0.j 8.+0.j 0.+0.j 0.+5.j]
Checking for complex number :
[ True False False False  True]
Checking for real number : 
[False  True  True  True False]
Checking for scalar type :
True
False


# Exercise 11

# 1.Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [21]:
import numpy as np
x = np.array([87, 98, -100, 23, -15, 56, 80])
y = np.array ([80, 56, -15, 23, -100, 98, 87])
print("Original numbers :")
print(x)
print(y)
print("Comparison - equal :")
print(np.equal(x,y))
print("Comparison - equal within a tolerance :")
print(np.allclose(x, y))

Original numbers :
[  87   98 -100   23  -15   56   80]
[  80   56  -15   23 -100   98   87]
Comparison - equal :
[False False False  True False False False]
Comparison - equal within a tolerance :
False


# 2.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [23]:
import numpy as np
x = np.array ([10, 20])
y = np.array([15, 25])
print("Original numbers :")
print(x)
print(y)
print ("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers :
[10 20]
[15 25]
Comparison - greater
[False False]
Comparison - greater_equal
[False False]
Comparison - less
[ True  True]
Comparison - less_equal
[ True  True]


# Exercise 12

# 1.Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays

In [26]:
import numpy as np
x = np.array([13, 24, 98, 0, 77, 65, 1000])
y = np.array([10, 2, 78, 0, 23, 1050, 6])
print("Original numbers :")
print(x)
print(y)
print("Comparison - equal :")
print(np.equal(x, y))
print("Comparison - equal within a tolerance")
print(np.allclose(x, y))

Original numbers :
[  13   24   98    0   77   65 1000]
[  10    2   78    0   23 1050    6]
Comparison - equal :
[False False False  True False False False]
Comparison - equal within a tolerance
False


# 2.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [28]:
import numpy as np
x = np.array([1,7,13,105])
print("Original array :")
print(x)
print("Size of the memory occupied by the array")
print("%d bytes" % (x.size * x.itemsize))

Original array :
[  1   7  13 105]
Size of the memory occupied by the array
16 bytes
