# Question and Answers

In [1]:
import numpy as np

1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
a = np.array([2,3,1,0,6,7])
a

array([2, 3, 1, 0, 6, 7])

In [3]:
for index,item in enumerate(a):
    if item==0:
        print('Zero value found at Index',index)
    else:
        print(item," is not zero")

2  is not zero
3  is not zero
1  is not zero
Zero value found at Index 3
6  is not zero
7  is not zero


2. Write a NumPy program to test whether any of the elements of a given array is non-zero

In [4]:
a = np.array([0,0,1,0,6,0])
a

array([0, 0, 1, 0, 6, 0])

In [6]:
for index,item in enumerate(a):
    if item>0:
        print('Zero value not found',index)
    else:
        print(item," is zero")

0  is zero
0  is zero
Zero value not found 2
0  is zero
Zero value not found 4
0  is zero


3. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [7]:
a = np.array([1, 0, np.nan, np.inf])

In [8]:
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


4. Write a NumPy program to test element-wise for positive or negative infinity.

In [9]:
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


5. Write a NumPy program to test element-wise for NaN of a given array.

In [10]:
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


6. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [16]:
a = np.array([2+1j, 1+0j, 2.5, 4, 2, 3j])
a

array([2. +1.j, 1. +0.j, 2.5+0.j, 4. +0.j, 2. +0.j, 0. +3.j])

In [17]:
print("Complex number:")
print(np.iscomplex(a))

Complex number:
[ True False False False False  True]


In [18]:
print("Real number:")
print(np.isreal(a))


Real number:
[False  True  True  True  True False]


In [20]:
print("Scalar type:")
print(np.isscalar(2.5))
print(np.isscalar([2.5]))

Scalar type:
True
False


7. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [21]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

False
True
False
False
True


8. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [22]:
x = np.array([4, 7])
y = np.array([4, 9])
print(x)
print(y)

[4 7]
[4 9]


In [23]:
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Comparison - greater
[False False]
Comparison - greater_equal
[ True False]
Comparison - less
[False  True]
Comparison - less_equal
[ True  True]


9. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [44]:
x = np.array([4, 21, 80, 90, 100, -15, 20, -10, 60, 32])
y = np.array([4, 21, 80, 90, 100, -15.00001, 20, -10, 60, 32])
print(x)
print(y)

[  4  21  80  90 100 -15  20 -10  60 100]
[  4.       21.       80.       90.      100.      -15.00001  20.
 -10.       60.      100.     ]


In [45]:
print("Comparison - equal:")
print(np.equal(x, y))

Comparison - equal:
[ True  True  True  True  True False  True  True  True  True]


In [46]:
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Comparison - equal within a tolerance:
True


10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [47]:
x = np.array([1, 7, 13, 105])
x

array([  1,   7,  13, 105])

In [49]:
print("%d bytes" % (x.size * x.itemsize))

16 bytes
