Task

1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [3]:
for item in a:
    if item == 0:
        print('Zero value found')
    else:
        print(item,'is not zero')

Zero value found
1 is not zero
2 is not zero
3 is not zero
4 is not zero
5 is not zero


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [6]:
b = np.array([1, 2, 3, 4, 5, 6, 0])
print(b)

[1 2 3 4 5 6 0]


In [7]:
for item in b:
    if item !=0:
        print(item, 'is non-zero')
    else:
        print('zero item found')

1 is non-zero
2 is non-zero
3 is non-zero
4 is non-zero
5 is non-zero
6 is non-zero
zero item found


In [33]:
print(np.any(b))

True


3. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [8]:
c = np.array([1, 0, np.nan, np.inf])
print(c)

[ 1.  0. nan inf]


In [9]:
print(np.isfinite(c))

[ True  True False False]


4. Write a NumPy program to test element-wise for positive or negative infinity.

In [12]:
d = np.array([89, 34, -3, np.inf])
print(d)
print(np.isinf(d))

[89. 34. -3. inf]
[False False False  True]


5. Write a NumPy program to test element-wise for NaN of a given array.

In [13]:
e = np.arange(25).reshape(5, 5) 

In [14]:
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
print(np.isnan(e))

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


6. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [16]:
f = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(f)

[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]


In [17]:
print(np.iscomplex(f))

[ True False False False False  True]


In [18]:
print(np.isreal(f))

[False  True  True  True  True False]


In [20]:
''' To check if a given number 4.3 is scalar type or not ''' 

print(np.isscalar(4.3))

True


7. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [23]:
g =np.array([1e10,1e-7])
h =np.array([1.00001e10,1e-8])

print(np.allclose(g, h))

False


8. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [24]:
i = np.array([3, 5, 6, 21])
j = np.array([2, 7, 78, 5])
print(i)
print(j)

[ 3  5  6 21]
[ 2  7 78  5]


In [25]:
print(np.greater(i, j))

[ True False False  True]


In [26]:
print(np.greater_equal(i,j))

[ True False False  True]


In [27]:
print(np.less(i, j))

[False  True  True False]


In [28]:
print(np.less_equal(i, j))

[False  True  True False]


9. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [29]:
k = np.array([74, 79, 85, 90, 150, -135, 120, -10, 60, 100])
l = np.array([74, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(k)
print(l)

[  74   79   85   90  150 -135  120  -10   60  100]
[  74.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]


In [30]:
print(np.equal(k, l))

[ True  True  True  True  True  True  True  True  True False]


In [31]:
print(np.allclose(k, l))

True


10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [32]:
m = np.array([1, 7, 13, 105])

print(m)

[  1   7  13 105]


In [34]:
print("%d bytes" % (m.size * m.itemsize))

16 bytes
